---
- hosts: all
  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
  pre_tasks:
    - yum:
        name: initscripts
        state: installed
  roles:
    - { role: ansible-role-aws-cli,
          aws_cli_system_user: "root" ,
          aws_cli_profile: "root" ,
          aws_cli_access_key: "xxx",
          aws_cli_secret_key: "xxx",
          aws_cli_region: "eu-west-1",
          aws_cli_format: "text"
      }
    - { role: ansible-aws-squid,
          aws_region: "ap-southeast-2",
          install_s3_bucket_name: "varutatthakornpun",
          squid_package: "squid-3.5.20-1.el6.x86_64.rpm",
      }
  tasks:
    - shell: service squid status
